---
- hosts: localhost
  gather_facts: false
  collections:
    - netapp.ontap
  vars_files: "{{ file }}"
  vars:
    login: &login
      hostname: "{{ cluster_ip }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false
  name: "Build Configurations: {{ cluster_name }}"

  tasks:
  - name: "Enable HA status for cluster"
    na_ontap_cluster_ha:
      state: present
      <<: *login

  - name: Set Login Message
    na_ontap_command:
      command: ["security login banner modify -vserver {{ cluster_name }} -message {{ motd }}"]
      <<: *login
    when: motd != None
    
  - name: Add licenses
    na_ontap_license:
      state: present
      license_codes: "{{ licenses |list }}"
      <<: *login

  - name: Zero Spares and Enable Auto-Assign
    na_ontap_command:
      command: ['set d -c off;  disk option modify -node ',"{{ hosts['node1'].name }}",' -autoassign on;disk option modify -node ',"{{ hosts['node2'].name }}",' -autoassign on; disk zerospares']
      <<: *login

  - name: Modify Service Processor Network
    na_ontap_service_processor_network:
      node: "{{ item.node }}"
      dhcp: none
      is_enabled: true
      address_type: ipv4
      state: present
      ip_address: "{{ item.ip_address }}"
      gateway_ip_address: "{{ item.gateway }}"
      netmask: "{{ item.netmask }}"
      <<: *login
    with_items:
      "{{ sp }}"
    when: sp != None

  - name: Create Aggregates
    na_ontap_aggregate:
      state: present
      service_state: online
      name: "{{ item.name }}"
      disk_count: "{{ item.diskcount }} "
      disk_type: "{{ item.disktype }}"
      raid_size: "{{ item.raidsize }}"
      raid_type: "{{ item.raidtype }}"
      nodes: "{{ item.node }}"
      <<: *login
    with_items:
      "{{ aggregates }}"
    when: aggregates != None

  - name: Apply hybrid mode for Aggregates
    na_ontap_command:
      command: ["aggr modify -aggregate {{ item.name }} -hybrid-enabled {{ item.hybrid }}"]
      <<: *login
    with_items:
      "{{ aggregates }}"
    when: aggregates != None

  - name: Create Storage Pool
    na_ontap_command:
      command: ["storage pool create -nodes {{ item.nodes }} -storage-pool {{ item.sp }} -disk-count {{ item.diskcount }} -disk-size {{ item.disksize }}"]
      <<: *login
    with_items:
      "{{ storagepool }}"
    when: storagepool != None

  - name: Add Storage Pool to Aggregate
    na_ontap_command:
      command: ["aggr add-disks -storage-pool sp1 -aggregate {{ item.name }} -allocation-units {{ item.allocationunits }} -raidtype {{ item.sp_raid }}"]
      <<: *login
    with_items:
      "{{ aggregates }}"
    when: (aggregates != None) and (item.allocationunits != None)

  - name: Create Vserver
    na_ontap_svm:
      state: present
      name: "{{ item.name }}"
      allowed_protocols: "{{ item.protocols }}"    
      <<: *login
    with_items:
      "{{ vservers }}"
    when: vservers != None
    tags: vserver

  - name: Create iscsi service
    netapp.ontap.na_ontap_iscsi:
      state: present
      service_state: started
      vserver: "{{ item.vserver }}"
      <<: *login

  - name: Create and Configure NFS server
    na_ontap_nfs:
      state: present
      service_state: started
      vserver: "{{ item.vserver }}"
      nfsv3: "{{ item.nfsv3 }}"
      nfsv4: "{{ item.nfsv4}}"
      nfsv41: "{{ item.nfsv41 }}"
      vstorage_state: "{{ item.vstorage }}"
      <<: *login
    with_items:
      "{{ nfs }}"
    when: nfs != None

  - name: Create CIFS server - Active Directory
    ignore_errors: yes
    na_ontap_cifs_server:
      state: present
      cifs_server_name: "{{ item.cifs_server_name}}"
      admin_user_name: "{{ item.admin_user }}"
      admin_password: "{{ item.admin_password }}"
      vserver: "{{ item.vserver }}"
      domain: "{{ item.domain }}"
      <<: *login
    with_items:
      "{{ cifsad }}"
    when: cifsad != None

  - name: Create CIFS share
    na_ontap_cifs:
      state: present
      share_name: "{{ item.share_name }}"
      path: "{{ item.vol_path }}"
      vserver: "{{ item.vserver }}"
      share_properties: browsable,oplocks
      symlink_properties: read_only,enable
      <<: *login
    with_items:
      "{{ cifsShares }}"
    when: cifsShares != None

  - name: Create Login Users and Unlock Vsadmin
    na_ontap_user:
      state: present
      name: "{{ item.username }}" 
      applications: "{{ item.apps }}"
      authentication_method: password
      set_password: "{{ item.password }}"
      lock_user: false
      role_name: "{{ item.role }}"
      vserver: "{{ item.vserver }}"
      <<: *login
    with_items:
      "{{ loginUsers }}"
    when: loginUsers != None
    tags:
      - vsadmin
  - name: Set NTP Server
    ignore_errors: yes
    na_ontap_ntp:
      state: present
      server_name: "{{ item.server_name }}"
      version: "{{ item.version }}"
      <<: *login
    with_items:
      "{{ ntp }}"
    when: ntp != None

  - name: Create Snapshot policy
    na_ontap_snapshot_policy:
      state: present
      name: "{{ item.name }}"
      schedule: "{{ item.schedule }}"
      count: "{{ item.count }}"
      enabled: True
      <<: *login
    with_items:
      "{{ snapshot_policy }}"
    when: snapshot_policy != None
    tags:
      - policy

  - name: Remove Ports from Default Broadcast Domain
    na_ontap_broadcast_domain_ports:
      ignore_errors: yes
      state: absent
      broadcast_domain: "Default"
      ports: "{{ item.node }}:{{ item.port }}"
      <<: *login
    with_items:
      "{{ ports }}"
    when: ports != None

  - name: Modify Net Port
    ignore_errors: yes
    na_ontap_net_port:
      state: present
      node: "{{ item.node }}"
      port: "{{ item.port }}"
      mtu: "{{ item.mtu }}"
      autonegotiate_admin: "{{ item.autonegotiate }}"
      flowcontrol_admin: "{{ item.flowcontrol }}"
      <<: *login
    with_items:
      "{{ ports }}"
    when: ports != None

  - name: Modify Net Port of ifgrp
    na_ontap_net_port:
      state: present
      node: "{{ item.node }}"
      port: "{{ item.name }}"
      mtu: "{{ item.mtu }}"
      <<: *login
    with_items:
      "{{ ifgrps }}"
    when: ifgrps != None

  - name: Create ifgrp
    na_ontap_net_ifgrp:
      state: present
      distribution_function: "{{ item.distribution_function }}" #goes to default
      mode: "{{ item.mode }}" #goes to default
      name: "{{ item.name }}"
      ports: "{{ item.ports }}"
      node: "{{ item.node }}"
      <<: *login
    with_items:
      "{{ ifgrps }}"
    when: ifgrps != None

  - name: Create VLAN
    na_ontap_net_vlan:
      state: present
      vlanid: "{{ item.vlanid }}"
      node: "{{ item.node }}"
      parent_interface: "{{ item.phy_interface }}"
      <<: *login
    with_items:
      "{{ vlans }}"
    when: vlans != None

  - name: create broadcast domain
    na_ontap_broadcast_domain:
      state: present
      broadcast_domain: "{{ item.name }}"
      mtu: "{{ item.mtu }}"
      ipspace: "Default"
      ports: "{{ item.ports }}"
      <<: *login
    with_items:
      "{{ bcasts }}"
    when: bcasts != None


  - name: Create interfaces
    na_ontap_interface:
      state: present
      interface_name: "{{ item.name }}"
      home_port: "{{ item.port }}"
      home_node: "{{ item.node }}"
      role: data
      protocols: "{{ item.protocols }}"
      admin_status: up
      address: "{{ item.address }}"
      netmask: "{{ item.netmask }}"
      dns_domain_name: "{{ item.dns_domain_name |default}}"
      vserver: "{{ item.vserver }}"
      <<: *login
    with_items:
      "{{ lifs }}"
    when: lifs != None
    tags:
      - lif

  - name: Create Routes
    na_ontap_net_routes:
      state: present
      vserver: "{{ item.vserver }}"
      destination: "{{ item.destination }}"
      gateway: "{{ item.gateway }}"
      metric: 20
      <<: *login
    with_items:
      "{{ routes }}"
    when: routes != None

  - name: Setup DNS
    na_ontap_dns:
      state: present
      vserver: "{{ item.vserver }}"
      domains: "{{ item.dns_domains }}"
      nameservers: "{{ item.dns_nameservers }}"
      #ontapi: "{{ ontap_facts.ontap_version }}"
      skip_validation: "true"
      <<: *login
    with_items:
      "{{ dns }}"
    when: dns != None

  - name: Modify Export Policy Default to 0.0.0.0/0
    na_ontap_export_policy_rule:
      state: present
      allow_suid: true
      client_match: "0.0.0.0/0"
      policy_name: "default"
      protocol: "nfs"
      ro_rule: "any"
      rw_rule: "None"
      super_user_security: "None"
      vserver: "{{ item.name }}"
      <<: *login
    with_items:
      "{{ vservers }}"
    when: vservers != None

  - name: Create Export Policy Rules
    na_ontap_export_policy_rule:
      state: present
      allow_suid: true
      client_match: "{{ item.client_match }}"
      policy_name: "{{ item.name }}"
      protocol: "nfs"
      ro_rule: "any"
      rw_rule: "any"
      super_user_security: "any"
      vserver: "{{ item.vserver }}"
      <<: *login
    with_items:
      "{{ exportrules }}"
    when: exportrules != None

  - name: Create igroup
    na_ontap_igroup:
      state: present
      name: "{{ item.name }}"
      initiator_group_type: "{{ item.initiator_group_type }}"
      os_type: "{{ item.os_type }}"
      initiator_names: "{{ item.initiator_names }}"
      vserver: "{{ item.vserver }}"
      <<: *login
    with_items:
      "{{ igroup }}"
    when: igroup != None
    tags:
      - igroup

  - name: Create Flexvol Volumes
    na_ontap_volume:
      state: present
      name: "{{ item.name }}"
      junction_path: "{{ item.junction_path }}"
      is_infinite: False
      aggregate_name: "{{ item.aggr }}"
      snapshot_policy: "{{ item.snapshot_policy }}"
      size: "{{ item.size }}"
      size_unit: gb
      space_guarantee: none
      policy: "{{ item.policy }}"
      percent_snapshot_space: "{{ item.snappercent }}"
      vserver: "{{ item.vserver }}"
      volume_security_style: "{{ item.securitystyle }}"
      wait_for_completion: false
      <<: *login
    with_items:
      "{{ volumes }}"
    when: (volumes != None)

  - name: Create Flexgroup Volumes
    na_ontap_volume:
      state: present
      name: "{{ item.name }}"
      junction_path: "/{{ item.name }}"
      is_infinite: False
      aggr_list: "{{ item.aggr_list }}"
      aggr_list_multiplier: "{{ item.aggr_list_multiplier }}"
      snapshot_policy: "{{ item.snapshot_policy }}"
      size: "{{ item.size }}"
      size_unit: gb
      space_guarantee: none
      policy: "{{ item.policy }}"
      percent_snapshot_space: "{{ item.snappercent }}"
      vserver: "{{ item.vserver }}"
      volume_security_style: "{{ item.securitystyle }}"
      wait_for_completion: false
      <<: *login
    with_items:
      "{{ FGvolumes }}"
    when: (FGvolumes != None)

  - name: Create Luns
    na_ontap_lun:
      state: present
      name: "{{ item.name }}"
      flexvol_name: "{{ item.flexvol_name }}"
      vserver: "{{ item.vserver }}"
      size: "{{ item.size }}"
      size_unit: gb
      os_type: "{{ item.os_type }}"
      space_reserve: "{{ item.space_reserve }}"
      space_allocation: "{{ item.space_allocation }}"
      <<: *login
    with_items:
      "{{ luns }}"
    when: (luns != None)

  - name: Create LUN mapping
    na_ontap_lun_map:
      state: present
      initiator_group_name: "{{ item.igroup }}"
      path: "/vol/{{ item.flexvol_name }}/{{ item.name }}"
      lun_id: "{{ item.lun_id }}"
      vserver: "{{ item.vserver }}"
      <<: *login
    with_items:
      "{{ luns }}"
    when: (luns != None)

  - name: Enable Volume efficiency
    na_ontap_volume_efficiency:
      state: present
      vserver: "{{ item.vserver }}"
      path: "/vol{{ item.junction_path }}"
      <<: *login
    with_items:
      "{{ volumes }}"
    when: (volumes != None) and (item.sis_enable == true)

  - name: Enable Volume efficiency - for Flexgroup
    na_ontap_volume_efficiency:
      state: present
      vserver: "{{ item.vserver }}"
      path: "/vol{{ item.junction_path }}"
      <<: *login
    with_items:
      "{{ FGvolumes }}"
    when: (FGvolumes != None) and (item.sis_enable == true)

  - name: Create SNMP community
    na_ontap_snmp:
      community_name: "{{ item.community_name }}"
      access_control: "{{ item.access_control }}"
      <<: *login
    with_items:
      "{{ snmp }}"
    when: snmp != None